name: PySpark Integration Tests

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  integration-tests:
    name: Run PySpark Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install uv Package
        run: |
          pip install --upgrade pip
          pip install uv==0.5.30

      - name: Install Dependencies
        run: |
          uv sync

      - name: Run Integration Tests
        run: |
          uv run pytest tests/integration -k "pyspark" -v
